name: 'asana_scrum'
version: '1.0.0'
config-version: 2

profile: 'default'

tests:
  +severity: warn  # all tests

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  asana_scrum:
    staging:
      materialized: view
    datasets:
      materialized: table
    
